---
- name: ldap clients
  hosts: combined
  become: true 
  tasks:
  - name: install ldap client
    yum:
      name: openldap-clients,nss-pam-ldapd,sssd
      state: latest
  - name: configure ldap clients
    shell:
      cmd: authconfig --enableldap --disableldapauth --disableldaptls --disableshadow --disablemd5 --ldapserver=prdx-ldap11.ziyotek1.local --ldapbasedn="dc=ziyotek1,dc=local" --enablemkhomedir --enablelocauthorize --update

