---
- name: Install and configure OpenLDAP Server
  hosts: prdx-ldap11
  become: true

  tasks:
    - name: openldap is present
      yum:
        name:
          - openldap
          - openldap-clients
          - openldap-servers
          - openssl
        state: present

    - name: openldap is started
      service:
        name: slapd
        state: started
        enabled: true

