---
- name: creating team user 
  become: true
  hosts: all
  tasks: 
    - name: Creating user
      user: name=Estalder password=password
    - name: Creating user
      user: name=Zafar password=password
    - name: Creating user
      user: name=Artem password=password
    - name: Creating user
      user: name=Yonnick password=password
    - name: Creating user
      user: name=Bekzod password=password
       


