---
- hosts: all
  tasks:
  - name: Install ntp
    yum: 
      name: ntp 
      state: latest
  - name: enable ntp
    service:
      name: ntpd
      enabled: true
      state: started
   
        

