galaxy_info:
  author: Christian Iuga
  description: Role to install and configuration ldap client
  company: edifixio
  license: GPL
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
      - all
      - any
      - 7
      - 6
  - name: Debian
    versions:
      - jessie
      - wheezy
  - name: RedHat
    versions:
      - all
      - any
      - 7
      - 6
  - name: Amazon
    version:
      - 2016.09
  galaxy_tags:
  - system
  - ldap
  - authentification
  - sssd
